### ISSUE TITLE
fingerprintManager is NULL

### ISSUE THREAD

**Issue by juleimisf** [amirarcane/lock-screen#11]
Can you add validation ? :
   if(fingerprintManager!= null)

in activity EnterPinActivity , line 399, some devices chrash

**Comment by jrcacd** [comment]
Please can you fix this?
We are also having the same problem

**Comment by ThiagoPierotti** [comment]
@amirarcane any idea on when this is going to be released on the maven repo?
I checked https://mvnrepository.com/artifact/com.amirarcane.lock-screen/lockscreen and the latest release was on June 2018.
