### ISSUE TITLE
Exception on unsupported fingerprint samsung device. 

### ISSUE THREAD

**Issue by VuHongHiep** [amirarcane/lock-screen#5]
Please finish checkForFingerPrint() if device is not supported.

if (!mFingerprintManager.isHardwareDetected()) {
                // If a fingerprint sensor isn’t available, then inform the user that they’ll be unable to use your app’s fingerprint functionality//
                // textView.setText("Your device doesn't support fingerprint authentication");
                mImageViewFingerView.setVisibility(View.GONE);
                mTextFingerText.setVisibility(View.GONE);
                return; // my suggestion
            }

Otherwise, exception will raise when call mFingerprintManager.hasEnrolledFingerprints() on SamSung J2-Prime if KEY_PIN is created.

**Comment by amirarcane** [comment]
You're right.
Check new version (2.0.0). It should be solved.
