### ISSUE TITLE
Wrong Pin Entered Count access  is private

### ISSUE THREAD

**Issue by abhishekgargx** [amirarcane/lock-screen#7]
private void checkPin(String pin) {
        if (Utils.sha256(pin).equals(getPinFromSharedPreferences())) {
            setResult(RESULT_OK);
            finish();
        } else {
            shake();

      //            mTryCount++;

            mTextAttempts.setText(getString(R.string.pinlock_wrongpin));
            mPinLockView.resetPinLockView();

      //            if (mTryCount == 1) {
      //                mTextAttempts.setText(getString(R.string.pinlock_firsttry));
     //                mPinLockView.resetPinLockView();
      //            } else if (mTryCount == 2) {
     //                mTextAttempts.setText(getString(R.string.pinlock_secondtry));
     //                mPinLockView.resetPinLockView();
     //            } else if (mTryCount > 2) {
     //                setResult(RESULT_TOO_MANY_TRIES);
     //                finish();
      //            }
         }
      }
All lines are commented , i need to use them in my code however these lines and come under private access of method checkPin() , Help ASAP.

**Comment by amirarcane** [comment]
Sorry for the late response.
Actually, they are a guide to help you implement TryCount. In most cases, there is no need to lock the device. So please fork the library or clone it and uncomment the lines for your use.
Thank you for using this library.
@Abhishekgarg727
