### ISSUE TITLE
how to remove the pin

### ISSUE THREAD

**Issue by kilicpl** [amirarcane/lock-screen#9]
Hi sir.  Thanks for the helpful code but how can we remove the pin with this library is that possible?
Thanks a lot again

**Comment by sanxy** [comment]
Yes it is possible. I was able to remove the pin using shared preference.
I saved the set pin into a shared preference using a boolean, then created another button with onClickListener and removed the stored key value stored earlier.
Check my sample used to remove the key from shared preference below:
SharedPreferences.Editor editor = getSharedPreferences(PACKAGE_NAME, MODE_PRIVATE).edit();
            editor.remove("pinSaved");
            editor.apply();

Then you can used the shared preference anywhere in your app.

**Comment by kilicpl** [comment]
thank you very much sir,  I solved with sth similiar.. And appreciated for
the great library again, that was a real lifesaver
Have a great day

**Comment by amirarcane** [comment]
@kilicpl Sorry for the late response and Thank you for using this library.
@sanxy You're right, Thank you for the clarification.
